apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argowf-artifacts
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/capafanwi/argocd.git
    targetRevision: HEAD
    path: non-helm/argowf-artifacts
    kustomize:
      namePrefix: argowf-artifacts-
  destination:
    namespace: argo-artifacts   # ask Vic for NS
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true