apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argowf-platform-comp
  namespace: argocd
spec:
  destination:
    namespace: cgs
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: helm/argowf-platform-comp
    # kustomize:
    #   version: v4.5.7
    repoURL:  https://github.com/capbancroft/cgs-argocd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true