apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/capbancroft/cgs-argocd.git
    targetRevision: HEAD
    path: non-helm/argowf-apps/1-script-example
    kustomize:
      namePrefix: argowf-artifacts-
  destination:
    namespace: cgs   
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true