apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mosquitto
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/capbancroft/cgs-argocd.git
    targetRevision: HEAD
    path: non-helm/mosquitto
    kustomize:
      namePrefix: mosquitto-
  destination:
    namespace: cgs 
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true