apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-security
data:
  dynamic-security.json: |
    {
      "clients":	[{
          "username":	"admin-user",
          "textName":	"Dynsec admin user",
          "password":	"WIKYq9Z13d+TJpsRSENDmNSTHXS2QvsATdS7vG3RUqxCrHCmFv3d8viecxaHmQBGk3lyQJ9UsJfl9sK/MvRF2A==",
          "salt":	"IMNhXxDcGjsQKr83",
          "iterations":	101,
          "roles":	[{
              "rolename":	"admin"
            }]
        }],
      "roles":	[{
          "rolename":	"admin",
          "acls":	[{
              "acltype":	"publishClientSend",
              "topic":	"$CONTROL/dynamic-security/#",
              "allow":	true
            }, {
              "acltype":	"publishClientReceive",
              "topic":	"$CONTROL/dynamic-security/#",
              "allow":	true
            }, {
              "acltype":	"subscribePattern",
              "topic":	"$CONTROL/dynamic-security/#",
              "allow":	true
            }, {
              "acltype":	"publishClientReceive",
              "topic":	"$SYS/#",
              "allow":	true
            }, {
              "acltype":	"subscribePattern",
              "topic":	"$SYS/#",
              "allow":	true
            }, {
              "acltype":	"publishClientReceive",
              "topic":	"#",
              "allow":	true
            }, {
              "acltype":	"subscribePattern",
              "topic":	"#",
              "allow":	true
            }, {
              "acltype":	"unsubscribePattern",
              "topic":	"#",
              "allow":	true
            }]
        }],
      "defaultACLAccess":	{
        "publishClientSend":	false,
        "publishClientReceive":	true,
        "subscribe":	false,
        "unsubscribe":	true
      }
    }